# Generated by Django 3.2 on 2024-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_titles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
